### ISSUE TITLE
OpenCV 3.3.0 doesn't work 

### ISSUE THREAD

**Issue by monajalal** [srianant/kalman_filter_multi_object_tracking#1]
Hey how can I get this work with OpenCV3.3.0?

Wed Nov 01 21:04:20 mona@nat-wireless-eduroam-guest-153-28:~/CS585/hw4/kalman_filter_multi_object_tracking$ python object_tracking.py 
OpenCV: Couldn't read video stream from file "data/TrackingBugs.mp4"
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /Users/travis/miniconda3/conda-bld/opencv_1506476120161/work/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10638
Traceback (most recent call last):
  File "object_tracking.py", line 117, in <module>
    main()
  File "object_tracking.py", line 63, in main
    centers = detector.Detect(frame)
  File "/Users/mona/CS585/hw4/kalman_filter_multi_object_tracking/detectors.py", line 48, in Detect
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: /Users/travis/miniconda3/conda-bld/opencv_1506476120161/work/opencv-3.3.0/modules/imgproc/src/color.cpp:10638: error: (-215) scn == 3 || scn == 4 in function cvtColor

Or do you know how to install OpenCV 3.0 for Anaconda Python?

**Comment by monajalal** [comment]
oh never mind. I just realized I didn't download the data. It could be downloaded from https://github.com/Smorodov/Multitarget-tracker/blob/master/data/TrackingBugs.mp4 
also it works with OpenCV 3.3.0:
```
Wed Nov 01 21:20:27 :~/CS585/hw4/kalman_filter_multi_object_tracking$ python
Python 3.6.2 |Anaconda custom (x86_64)| (default, Jul 20 2017, 13:14:59)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'3.3.0'
>>> print(cv2.getBuildInformation())

General configuration for OpenCV 3.3.0 =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            /Users/travis/miniconda3/conda-bld/opencv_1506476120161/work/opencv-3.3.0/opencv_contrib-3.3.0/modules
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2017-09-27T01:42:15Z
    Host:                        Darwin 14.5.0 x86_64
    CMake:                       3.9.3
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 AVX AVX2
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2
      SSE4_1 (2 files):          + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (7 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  (ver 6.1.0.6020053)
    C++ flags (Release):         -arch x86_64 -mmacosx-version-min=10.9 -stdlib=libc++ -m64   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -arch x86_64 -mmacosx-version-min=10.9 -stdlib=libc++ -m64   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
    C flags (Release):           -arch x86_64 -mmacosx-version-min=10.9 -m64   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -arch x86_64 -mmacosx-version-min=10.9 -m64   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -arch x86_64 -headerpad_max_install_names -mmacosx-version-min=10.9 -lc++ -Wl,-rpath,/Users/mona/anaconda/lib -L/Users/mona/anaconda/lib
    Linker flags (Debug):        -arch x86_64 -headerpad_max_install_names -mmacosx-version-min=10.9 -lc++ -Wl,-rpath,/Users/mona/anaconda/lib -L/Users/mona/anaconda/lib
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          /Users/mona/anaconda/lib/libopenblas.dylib /Users/mona/anaconda/lib/libwebp.dylib /Users/mona/anaconda/lib/libpng.dylib /Users/mona/anaconda/lib/libtiff.dylib /Users/mona/anaconda/lib/libjasper.dylib /Users/mona/anaconda/lib/libjpeg.dylib avcodec avformat avutil swscale avresample -framework VideoDecodeAcceleration bz2 -framework Cocoa -framework Accelerate -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreVideo -framework QuartzCore freetype harfbuzz /Users/mona/anaconda/lib/libhdf5.dylib /usr/lib/libc++.dylib /usr/lib/libpthread.dylib /Users/mona/anaconda/lib/libz.dylib /usr/lib/libdl.dylib /usr/lib/libm.dylib
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 core flann hdf imgproc ml objdetect phase_unwrapping photo plot reg surface_matching video xphoto bgsegm dnn face freetype fuzzy img_hash imgcodecs shape videoio xobjdetect highgui superres bioinspired dpm features2d line_descriptor saliency text calib3d ccalib datasets rgbd stereo structured_light tracking videostab xfeatures2d ximgproc aruco optflow stitching python3
    Disabled:                    world contrib_world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 ts viz cnn_3dobj cvv dnn_modern matlab sfm

  GUI:
    QT:                          NO
    Cocoa:                       YES
    OpenGL support:              NO
    VTK support:                 NO

  Media I/O:
    ZLib:                        /Users/mona/anaconda/lib/libz.dylib (ver 1.2.8)
    JPEG:                        /Users/mona/anaconda/lib/libjpeg.dylib (ver 90)
    WEBP:                        /Users/mona/anaconda/lib/libwebp.dylib (ver encoder: 0x0209)
    PNG:                         /Users/mona/anaconda/lib/libpng.dylib (ver 1.6.28)
    TIFF:                        /Users/mona/anaconda/lib/libtiff.dylib (ver 42 - 4.0.7)
    JPEG 2000:                   /Users/mona/anaconda/lib/libjasper.dylib (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)
    GDAL:                        NO
    GDCM:                        NO

  Video I/O:
    DC1394 1.x:                  NO
    DC1394 2.x:                  NO
    FFMPEG:                      YES
      avcodec:                   YES (ver 57.64.101)
      avformat:                  YES (ver 57.56.101)
      avutil:                    YES (ver 55.34.101)
      swscale:                   YES (ver 4.2.100)
      avresample:                YES (ver 3.1.0)
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    Aravis SDK:                  NO
    AVFoundation:                YES
    V4L/V4L2:                    NO/NO
    XIMEA:                       NO
    Intel Media SDK:             NO
    gPhoto2:                     NO

  Parallel framework:            GCD

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Use Intel IPP:               2017.0.2 [2017.0.2]
               at:               /Users/travis/miniconda3/conda-bld/opencv_1506476120161/work/opencv-3.3.0/build/3rdparty/ippicv/ippicv_mac
    Use Intel IPP IW:            prebuilt binaries (2017.0.2)
    Use Intel IPP Async:         NO
    Use VA:                      NO
    Use Intel VA-API/OpenCL:     NO
    Use Lapack:                  YES (/Users/mona/anaconda/lib/libopenblas.dylib)
    Use Eigen:                   YES (ver 3.2.8)
    Use Cuda:                    NO
    Use OpenCL:                  NO
    Use OpenVX:                  NO
    Use custom HAL:              NO

  Python 2:
    Interpreter:                 NO

  Python 3:
    Interpreter:                 /Users/mona/anaconda/bin/python (ver 3.6.2)
    Libraries:                   /Users/mona/anaconda/lib/libpython3.6m.dylib (ver 3.6.2)
    numpy:                       /Users/mona/anaconda/lib/python3.6/site-packages/numpy/core/include (ver 1.8.2)
    packages path:               /Users/mona/anaconda/lib/python3.6/site-packages

  Python (for build):            /Users/mona/anaconda/bin/python

  Java:
    ant:                         NO
    JNI:                         /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/JavaVM.framework/Headers
    Java wrappers:               NO
    Java tests:                  NO

  Matlab:                        NO

  Tests and samples:
    Tests:                       NO
    Performance tests:           NO
    C/C++ Examples:              NO

  Install path:                  /Users/mona/anaconda

  cvconfig.h is in:              /Users/travis/miniconda3/conda-bld/opencv_1506476120161/work/opencv-3.3.0/build
-----------------------------------------------------------------


>>>
```
